; Lines starting with semicolons are comments.
[Admin]
; Setting this to false stops the game from loading the DLL.
Enabled=true
[AutoUpdateCityThumbnails]
; Write the region and city info to the plugin's log file. Defaults to true.
LogCityInfo=true
; Pause the city before saving it. Defaults to true.
PauseCityBeforeSave=true
